// utils/badges.js

export const badgeRules = [
  // 🧩 1. MEDIA ADDITION BADGES (overall progress)
  {
    id: "first_entry",
    name: "First Entry",
    type: "all",
    threshold: 1,
    icon: "🌟",
    description: "Added your first media entry — welcome aboard!",
  },
  {
    id: "media_collector",
    name: "Media Collector",
    type: "all",
    threshold: 10,
    icon: "📦",
    description: "Added 10 total entries — you're on a roll!",
  },
  {
    id: "media_enthusiast",
    name: "Media Enthusiast",
    type: "all",
    threshold: 25,
    icon: "🎯",
    description: "25 total entries — growing your collection fast!",
  },
  {
    id: "media_master",
    name: "Media Master",
    type: "all",
    threshold: 50,
    icon: "🏆",
    description: "50 entries added — you’re a true media explorer!",
  },
  {
    id: "media_elite",
    name: "Media Elite",
    type: "all",
    threshold: 100,
    icon: "💎",
    description: "100 total entries — you're reaching pro level!",
  },
  {
    id: "media_legend",
    name: "Media Legend",
    type: "all",
    threshold: 200,
    icon: "🔥",
    description: "200 total entries — passion at full power!",
  },
  {
    id: "media_icon",
    name: "Media Icon",
    type: "all",
    threshold: 300,
    icon: "👑",
    description: "300 total entries — your taste defines culture!",
  },
  {
    id: "media_grandmaster",
    name: "Media Grandmaster",
    type: "all",
    threshold: 400,
    icon: "🌌",
    description: "400 total entries — exploring every corner of media!",
  },
  {
    id: "media_legendary_collector",
    name: "Legendary Collector",
    type: "all",
    threshold: 500,
    icon: "💫",
    description: "500 total entries — your dedication is unmatched!",
  },
  {
    id: "media_immortal",
    name: "Media Immortal",
    type: "all",
    threshold: 1000,
    icon: "⚡",
    description: "1000 total entries — a timeless legend of media!",
  },

  // 🎬 2. TYPE-BASED BADGES
  {
    id: "movie_lover",
    name: "Movie Lover",
    type: "movie",
    threshold: 10,
    icon: "🎬",
    description: "Added 10 movies — cinema buff in the making!",
  },
  {
    id: "movie_enthusiast",
    name: "Movie Enthusiast",
    type: "movie",
    threshold: 20,
    icon: "🎬",
    description: "Added 20 movies — consistent and growing taste!",
  },
  {
    id: "movie_collector",
    name: "Movie Collector",
    type: "movie",
    threshold: 50,
    icon: "🎬",
    description: "Added 50 movies — deeply invested!",
  },
  {
    id: "movie_expert",
    name: "Movie Expert",
    type: "movie",
    threshold: 100,
    icon: "🎬",
    description: "Added 100 movies — true expert of your kind!",
  },
  {
    id: "movie_pro",
    name: "Movie Pro",
    type: "movie",
    threshold: 200,
    icon: "🎬",
    description: "Added 200 movies — unstoppable dedication!",
  },
  {
    id: "movie_legend",
    name: "Movie Legend",
    type: "movie",
    threshold: 300,
    icon: "🎬",
    description: "Added 300 movies — mastery unlocked!",
  },
  {
    id: "movie_icon",
    name: "Movie Icon",
    type: "movie",
    threshold: 400,
    icon: "🎬",
    description: "Added 400 movies — shaping the culture!",
  },
  {
    id: "movie_grandmaster",
    name: "Movie Grandmaster",
    type: "movie",
    threshold: 500,
    icon: "🎬",
    description: "Added 500 movies — your passion is unmatched!",
  },
  {
    id: "movie_immortal",
    name: "Movie Immortal",
    type: "movie",
    threshold: 1000,
    icon: "🎬",
    description: "Added 1000 movies — you’re a timeless legend!",
  },

  // 📺 SERIES
  {
    id: "series_lover",
    name: "Series Lover",
    type: "series",
    threshold: 10,
    icon: "📺",
    description: "Added 10 series — binge mode activated!",
  },
  {
    id: "series_enthusiast",
    name: "Series Enthusiast",
    type: "series",
    threshold: 20,
    icon: "📺",
    description: "Added 20 series — consistent and growing taste!",
  },
  {
    id: "series_collector",
    name: "Series Collector",
    type: "series",
    threshold: 50,
    icon: "📺",
    description: "Added 50 series — deeply invested!",
  },
  {
    id: "series_expert",
    name: "Series Expert",
    type: "series",
    threshold: 100,
    icon: "📺",
    description: "Added 100 series — true expert of your kind!",
  },
  {
    id: "series_pro",
    name: "Series Pro",
    type: "series",
    threshold: 200,
    icon: "📺",
    description: "Added 200 series — unstoppable dedication!",
  },
  {
    id: "series_legend",
    name: "Series Legend",
    type: "series",
    threshold: 300,
    icon: "📺",
    description: "Added 300 series — mastery unlocked!",
  },
  {
    id: "series_icon",
    name: "Series Icon",
    type: "series",
    threshold: 400,
    icon: "📺",
    description: "Added 400 series — shaping the culture!",
  },
  {
    id: "series_grandmaster",
    name: "Series Grandmaster",
    type: "series",
    threshold: 500,
    icon: "📺",
    description: "Added 500 series — your passion is unmatched!",
  },
  {
    id: "series_immortal",
    name: "Series Immortal",
    type: "series",
    threshold: 1000,
    icon: "📺",
    description: "Added 1000 series — you’re a timeless legend!",
  },

  // 📚 BOOKS
  {
    id: "book_lover",
    name: "Book Lover",
    type: "book",
    threshold: 10,
    icon: "📚",
    description: "Added 10 books — reading legend!",
  },
  {
    id: "book_enthusiast",
    name: "Book Enthusiast",
    type: "book",
    threshold: 20,
    icon: "📚",
    description: "Added 20 books — consistent and growing taste!",
  },
  {
    id: "book_collector",
    name: "Book Collector",
    type: "book",
    threshold: 50,
    icon: "📚",
    description: "Added 50 books — bibliophile vibes!",
  },
  {
    id: "book_expert",
    name: "Book Expert",
    type: "book",
    threshold: 100,
    icon: "📚",
    description: "Added 100 books — true expert of your kind!",
  },
  {
    id: "book_pro",
    name: "Book Pro",
    type: "book",
    threshold: 200,
    icon: "📚",
    description: "Added 200 books — unstoppable dedication!",
  },
  {
    id: "book_legend",
    name: "Book Legend",
    type: "book",
    threshold: 300,
    icon: "📚",
    description: "Added 300 books — mastery unlocked!",
  },
  {
    id: "book_icon",
    name: "Book Icon",
    type: "book",
    threshold: 400,
    icon: "📚",
    description: "Added 400 books — shaping the culture!",
  },
  {
    id: "book_grandmaster",
    name: "Book Grandmaster",
    type: "book",
    threshold: 500,
    icon: "📚",
    description: "Added 500 books — your passion is unmatched!",
  },
  {
    id: "book_immortal",
    name: "Book Immortal",
    type: "book",
    threshold: 1000,
    icon: "📚",
    description: "Added 1000 books — you’re a timeless legend!",
  },

  // 🎮 GAMES
  {
    id: "game_lover",
    name: "Game Lover",
    type: "game",
    threshold: 10,
    icon: "🎮",
    description: "Added 10 games — unstoppable gamer!",
  },
  {
    id: "game_enthusiast",
    name: "Game Enthusiast",
    type: "game",
    threshold: 20,
    icon: "🎮",
    description: "Added 20 games — consistent and growing taste!",
  },
  {
    id: "game_collector",
    name: "Game Collector",
    type: "game",
    threshold: 50,
    icon: "🎮",
    description: "Added 50 games — deeply invested!",
  },
  {
    id: "game_expert",
    name: "Game Expert",
    type: "game",
    threshold: 100,
    icon: "🎮",
    description: "Added 100 games — true expert of your kind!",
  },
  {
    id: "game_pro",
    name: "Game Pro",
    type: "game",
    threshold: 200,
    icon: "🎮",
    description: "Added 200 games — unstoppable dedication!",
  },
  {
    id: "game_legend",
    name: "Game Legend",
    type: "game",
    threshold: 300,
    icon: "🎮",
    description: "Added 300 games — mastery unlocked!",
  },
  {
    id: "game_icon",
    name: "Game Icon",
    type: "game",
    threshold: 400,
    icon: "🎮",
    description: "Added 400 games — shaping the culture!",
  },
  {
    id: "game_grandmaster",
    name: "Game Grandmaster",
    type: "game",
    threshold: 500,
    icon: "🎮",
    description: "Added 500 games — your passion is unmatched!",
  },
  {
    id: "game_immortal",
    name: "Game Immortal",
    type: "game",
    threshold: 1000,
    icon: "🎮",
    description: "Added 1000 games — you’re a timeless legend!",
  },
  // 🎞️ ANIME BADGES
  {
    id: "anime_lover",
    name: "Anime Lover",
    type: "anime",
    threshold: 10,
    icon: "🎞️",
    description: "Added 10 anime — otaku journey begins!",
  },
  {
    id: "anime_enthusiast",
    name: "Anime Enthusiast",
    type: "anime",
    threshold: 20,
    icon: "🎞️",
    description: "Added 20 anime — consistent and growing taste!",
  },
  {
    id: "anime_collector",
    name: "Anime Collector",
    type: "anime",
    threshold: 50,
    icon: "🎞️",
    description: "Added 50 anime — deeply immersed in the world of animation!",
  },
  {
    id: "anime_expert",
    name: "Anime Expert",
    type: "anime",
    threshold: 100,
    icon: "🎞️",
    description: "Added 100 anime — a true anime connoisseur!",
  },
  {
    id: "anime_pro",
    name: "Anime Pro",
    type: "anime",
    threshold: 200,
    icon: "🎞️",
    description: "Added 200 anime — your watchlist never ends!",
  },
  {
    id: "anime_legend",
    name: "Anime Legend",
    type: "anime",
    threshold: 300,
    icon: "🎞️",
    description: "Added 300 anime — you live and breathe anime!",
  },
  {
    id: "anime_icon",
    name: "Anime Icon",
    type: "anime",
    threshold: 400,
    icon: "🎞️",
    description: "Added 400 anime — influencing anime culture itself!",
  },
  {
    id: "anime_grandmaster",
    name: "Anime Grandmaster",
    type: "anime",
    threshold: 500,
    icon: "🎞️",
    description: "Added 500 anime — your dedication is unmatched!",
  },
  {
    id: "anime_immortal",
    name: "Anime Immortal",
    type: "anime",
    threshold: 1000,
    icon: "🎞️",
    description: "Added 1000 anime — a timeless legend of otaku culture!",
  },

  // 🌈 3. DIVERSITY BADGES (unique content variety)
 // 🌈 3. DIVERSITY BADGES (expanded multi-tier progression)

// 🎭 GENRE DIVERSITY
{
  id: "genre_explorer",
  name: "Genre Explorer",
  type: "all",
  threshold: 8,
  icon: "🎭",
  description: "Added media in 8 unique genres — diverse taste unlocked!",
},
{
  id: "genre_connoisseur",
  name: "Genre Connoisseur",
  type: "all",
  threshold: 15,
  icon: "🎭",
  description: "Explored 15 unique genres — variety is your strength!",
},
{
  id: "genre_master",
  name: "Genre Master",
  type: "all",
  threshold: 25,
  icon: "🎭",
  description: "25 genres experienced — an encyclopedia of taste!",
},
{
  id: "genre_grandmaster",
  name: "Genre Grandmaster",
  type: "all",
  threshold: 35,
  icon: "🎭",
  description: "35 genres explored — a true cultural polymath!",
},
{
  id: "genre_omnivore",
  name: "Genre Omnivore",
  type: "all",
  threshold: 50,
  icon: "🎭",
  description: "50 unique genres — you’ve mastered diversity itself!",
},

// 🧭 PLATFORM DIVERSITY
{
  id: "platform_hopper",
  name: "Platform Hopper",
  type: "all",
  threshold: 5,
  icon: "🧭",
  description: "Used 5 different platforms — explorer mode!",
},
{
  id: "platform_explorer",
  name: "Platform Explorer",
  type: "all",
  threshold: 10,
  icon: "🧭",
  description: "10 platforms — you’re discovering new sources constantly!",
},
{
  id: "platform_master",
  name: "Platform Master",
  type: "all",
  threshold: 15,
  icon: "🧭",
  description: "15 platforms — you’re a digital wanderer!",
},
{
  id: "platform_grandmaster",
  name: "Platform Grandmaster",
  type: "all",
  threshold: 25,
  icon: "🧭",
  description: "25 platforms — a true media nomad!",
},
{
  id: "platform_omnivore",
  name: "Platform Omnivore",
  type: "all",
  threshold: 40,
  icon: "🧭",
  description: "40 platforms — your reach spans the whole media world!",
},

// 🌈 MOOD DIVERSITY
{
  id: "mood_explorer",
  name: "Mood Explorer",
  type: "all",
  threshold: 5,
  icon: "🌈",
  description: "Logged 5 different moods — emotional range unlocked!",
},
{
  id: "mood_seeker",
  name: "Mood Seeker",
  type: "all",
  threshold: 10,
  icon: "🌈",
  description: "10 moods — an expressive and introspective viewer!",
},
{
  id: "mood_master",
  name: "Mood Master",
  type: "all",
  threshold: 15,
  icon: "🌈",
  description: "15 moods — you experience every emotion through media!",
},
{
  id: "mood_grandmaster",
  name: "Mood Grandmaster",
  type: "all",
  threshold: 25,
  icon: "🌈",
  description: "25 moods — you feel the full human spectrum!",
},
{
  id: "mood_empath",
  name: "Mood Empath",
  type: "all",
  threshold: 40,
  icon: "🌈",
  description: "40 moods — your empathy transcends storytelling!",
},

// 🌍 LANGUAGE DIVERSITY
{
  id: "language_traveler",
  name: "Language Traveler",
  type: "all",
  threshold: 5,
  icon: "🌍",
  description: "Watched or read in 5 different languages — global citizen!",
},
{
  id: "language_explorer",
  name: "Language Explorer",
  type: "all",
  threshold: 10,
  icon: "🌍",
  description: "Explored 10 languages — multilingual marvel!",
},
{
  id: "language_master",
  name: "Language Master",
  type: "all",
  threshold: 20,
  icon: "🌍",
  description: "20 languages — media polyglot unlocked!",
},
{
  id: "language_grandmaster",
  name: "Language Grandmaster",
  type: "all",
  threshold: 30,
  icon: "🌍",
  description: "30 languages — a cultural bridge through stories!",
},
{
  id: "language_omniglot",
  name: "Language Omniglot",
  type: "all",
  threshold: 50,
  icon: "🌍",
  description: "50 languages — global mastery achieved!",
},

  /// 🥇 4. FIRST-TIME CATEGORY BADGES (Expanded Multi-Tier System)

// 🎭 GENRE ADDITIONS
{
  id: "first_genre_added",
  name: "Genre Beginner",
  type: "genre",
  threshold: 1,
  icon: "🎭",
  description: "Added your first genre — your taste journey begins!",
},
{
  id: "genre_explorer_plus",
  name: "Genre Explorer+",
  type: "genre",
  threshold: 5,
  icon: "🎭",
  description: "Added 5 unique genres — branching into new interests!",
},
{
  id: "genre_collector",
  name: "Genre Collector",
  type: "genre",
  threshold: 10,
  icon: "🎭",
  description: "Added 10 unique genres — truly diverse in taste!",
},
{
  id: "genre_expert",
  name: "Genre Expert",
  type: "genre",
  threshold: 20,
  icon: "🎭",
  description: "Added 20 genres — your taste knows no limits!",
},
{
  id: "genre_legend",
  name: "Genre Legend",
  type: "genre",
  threshold: 30,
  icon: "🎭",
  description: "30 genres — a cultural curator with unmatched range!",
},

// 🧭 PLATFORM ADDITIONS
{
  id: "first_platform_added",
  name: "Platform Starter",
  type: "platform",
  threshold: 1,
  icon: "🧭",
  description: "Added your first platform — exploring new media sources!",
},
{
  id: "platform_explorer_plus",
  name: "Platform Explorer+",
  type: "platform",
  threshold: 5,
  icon: "🧭",
  description: "Added 5 platforms — expanding your horizons!",
},
{
  id: "platform_collector",
  name: "Platform Collector",
  type: "platform",
  threshold: 10,
  icon: "🧭",
  description: "Added 10 platforms — ultimate multi-platform user!",
},
{
  id: "platform_expert",
  name: "Platform Expert",
  type: "platform",
  threshold: 15,
  icon: "🧭",
  description: "Added 15 platforms — a veteran of media exploration!",
},
{
  id: "platform_legend",
  name: "Platform Legend",
  type: "platform",
  threshold: 25,
  icon: "🧭",
  description: "25 platforms — you’ve seen it all!",
},

// 🌍 LANGUAGE ADDITIONS
{
  id: "first_language_added",
  name: "Language Explorer",
  type: "language",
  threshold: 1,
  icon: "🌍",
  description: "Added your first language — multilingual adventure starts!",
},
{
  id: "language_collector",
  name: "Language Collector",
  type: "language",
  threshold: 5,
  icon: "🌍",
  description: "Added 5 languages — global media enthusiast!",
},
{
  id: "language_master",
  name: "Language Master",
  type: "language",
  threshold: 10,
  icon: "🌍",
  description: "Added 10 languages — true multilingual watcher!",
},
{
  id: "language_scholar",
  name: "Language Scholar",
  type: "language",
  threshold: 15,
  icon: "🌍",
  description: "15 languages — your curiosity spans the globe!",
},
{
  id: "language_legend",
  name: "Language Legend",
  type: "language",
  threshold: 25,
  icon: "🌍",
  description: "25 languages — cultural fluency achieved!",
},

// 🌈 MOOD ADDITIONS
{
  id: "first_mood_logged",
  name: "Mood Starter",
  type: "mood",
  threshold: 1,
  icon: "🌈",
  description: "Logged your first mood — discovering your vibe!",
},
{
  id: "mood_collector",
  name: "Mood Collector",
  type: "mood",
  threshold: 5,
  icon: "🌈",
  description: "Logged 5 moods — feeling the full spectrum!",
},
{
  id: "mood_master_plus",
  name: "Mood Master+",
  type: "mood",
  threshold: 10,
  icon: "🌈",
  description: "Logged 10 moods — emotionally aware storyteller!",
},
{
  id: "mood_expert_plus",
  name: "Mood Expert+",
  type: "mood",
  threshold: 15,
  icon: "🌈",
  description: "Logged 15 moods — a master of emotional range!",
},
{
  id: "mood_legend",
  name: "Mood Legend",
  type: "mood",
  threshold: 25,
  icon: "🌈",
  description: "Logged 25 moods — emotionally fluent in every genre!",
},


// 🤝 5. SOCIAL BADGES — FOLLOWING OTHERS (Expanded Tier System)
{
  id: "friendly_follower",
  name: "Friendly Follower",
  type: "social",
  threshold: 1,
  icon: "🤝",
  description: "Followed your first user — connections begin!",
},
{
  id: "community_member",
  name: "Community Member",
  type: "social",
  threshold: 5,
  icon: "💬",
  description: "Followed 5 users — part of the community!",
},
{
  id: "social_explorer",
  name: "Social Explorer",
  type: "social",
  threshold: 10,
  icon: "🎉",
  description: "Followed 10 users — social butterfly!",
},
{
  id: "social_connector",
  name: "Social Connector",
  type: "social",
  threshold: 20,
  icon: "🔗",
  description: "Followed 20 users — building meaningful networks!",
},
{
  id: "network_builder",
  name: "Network Builder",
  type: "social",
  threshold: 30,
  icon: "🌐",
  description: "Followed 30 users — expanding your social world!",
},
{
  id: "community_champion",
  name: "Community Champion",
  type: "social",
  threshold: 50,
  icon: "🏅",
  description: "Followed 50 users — fully engaged in the community!",
},
{
  id: "super_connector",
  name: "Super Connector",
  type: "social",
  threshold: 75,
  icon: "🚀",
  description: "Followed 75 users — inspiring interaction everywhere!",
},
{
  id: "social_legend",
  name: "Social Legend",
  type: "social",
  threshold: 100,
  icon: "👑",
  description: "Followed 100 users — true pillar of the community!",
},


  // 💫 6. POPULARITY BADGES — BEING FOLLOWED (Expanded Tiers)
{
  id: "rising_star",
  name: "Rising Star",
  type: "followers",
  threshold: 5,
  icon: "🌟",
  description: "Gained 5 followers — people love your taste!",
},
{
  id: "trendsetter",
  name: "Trendsetter",
  type: "followers",
  threshold: 15,
  icon: "🔥",
  description: "15 followers — your profile is trending!",
},
{
  id: "influencer",
  name: "Influencer",
  type: "followers",
  threshold: 30,
  icon: "👑",
  description: "30 followers — your opinions shape the community!",
},
{
  id: "notable_creator",
  name: "Notable Creator",
  type: "followers",
  threshold: 50,
  icon: "🏅",
  description: "50 followers — your presence stands out in the feed!",
},
{
  id: "celebrity_member",
  name: "Celebrity Member",
  type: "followers",
  threshold: 75,
  icon: "💫",
  description: "75 followers — a recognized name in the community!",
},
{
  id: "popular_icon",
  name: "Popular Icon",
  type: "followers",
  threshold: 100,
  icon: "🚀",
  description: "100 followers — a true influencer in MediaVerse!",
},


  /// 🎭 7. GENRE-SPECIFIC BADGES (by genre progress)
// Scales per genre — 5, 10, 25, 50, 100
// Extend the genre list as your platform grows
...[
  "Action",
  "Romance",
  "Horror",
  "Comedy",
  "Drama",
  "Sci-Fi",
  "Fantasy",
  "Thriller",
  "Adventure",
  "Mystery",
  "Documentary",
  "Animation",
  "Crime",
  "Historical",
].flatMap((genre) => [
  {
    id: `${genre.toLowerCase()}_fan_5`,
    name: `${genre} Enthusiast`,
    type: "genre",
    threshold: 5,
    icon: "🎭",
    description: `Added 5 ${genre} entries — your journey begins!`,
  },
  {
    id: `${genre.toLowerCase()}_fan_10`,
    name: `${genre} Lover`,
    type: "genre",
    threshold: 10,
    icon: "🔥",
    description: `Added 10 ${genre} entries — passion awakened!`,
  },
  {
    id: `${genre.toLowerCase()}_fan_25`,
    name: `${genre} Buff`,
    type: "genre",
    threshold: 25,
    icon: "⭐",
    description: `25 ${genre} entries — your taste is evolving!`,
  },
  {
    id: `${genre.toLowerCase()}_fan_50`,
    name: `${genre} Expert`,
    type: "genre",
    threshold: 50,
    icon: "🏅",
    description: `50 ${genre} entries — mastery level achieved!`,
  },
  {
    id: `${genre.toLowerCase()}_fan_100`,
    name: `${genre} Master`,
    type: "genre",
    threshold: 100,
    icon: "👑",
    description: `100 ${genre} entries — you’ve become a true ${genre} master!`,
  },
]),


  // 🏆 8. COMBINED GENRE PROGRESSION BADGES
  {
    id: "genre_collector_5",
    name: "Genre Explorer",
    type: "all",
    threshold: 5,
    icon: "🎭",
    description: "Added 5 genres — exploring your tastes!",
  },
  {
    id: "genre_collector_10",
    name: "Genre Connoisseur",
    type: "all",
    threshold: 10,
    icon: "🏅",
    description: "10 genres explored — your taste is unmatched!",
  },
  {
    id: "genre_collector_25",
    name: "Genre Master",
    type: "all",
    threshold: 25,
    icon: "👑",
    description: "25 genres — a world of stories under your belt!",
  },
  {
    id: "genre_collector_50",
    name: "Genre Historian",
    type: "all",
    threshold: 50,
    icon: "📚",
    description: "50 genres — you've seen it all!",
  },
  {
    id: "genre_collector_100",
    name: "Ultimate Genre Guru",
    type: "all",
    threshold: 100,
    icon: "🌌",
    description: "100 genres — beyond mastery!",
  },
    {
    id: "review_writer",
    name: "Critic in the Making",
    type: "experience",
    threshold: 1,
    icon: "📝",
    description: "Added your first review or note — sharing your thoughts!",
  },
  {
    id: "note_taker",
    name: "Detail Lover",
    type: "experience",
    threshold: 10,
    icon: "🗒️",
    description: "Added notes for 10 entries — attention to detail!",
  },
  {
    id: "deep_critic",
    name: "Insightful Reviewer",
    type: "experience",
    threshold: 25,
    icon: "💬",
    description: "25 notes or reviews — your insights stand out!",
  },
  {
    id: "veteran_reviewer",
    name: "Veteran Reviewer",
    type: "experience",
    threshold: 50,
    icon: "🏆",
    description: "50 reviews written — your opinion carries weight!",
  },
  {
    id: "master_reviewer",
    name: "Master Reviewer",
    type: "experience",
    threshold: 100,
    icon: "🎯",
    description: "100 reviews — the community looks up to your words!",
  },

  // 🏷️ 8. CATEGORY EXPLORATION BADGES
  {
    id: "multi_type_explorer",
    name: "Multi-Media Explorer",
    type: "exploration",
    threshold: 4,
    icon: "🧩",
    description: "Added entries in 4 different types — variety seeker!",
  },
  {
    id: "diverse_collector",
    name: "Diverse Collector",
    type: "exploration",
    threshold: 8,
    icon: "🎭",
    description: "Added entries across 8 genres — broad-minded taste!",
  },
  {
    id: "balanced_collector",
    name: "Balanced Collector",
    type: "exploration",
    threshold: 20,
    icon: "⚖️",
    description: "Maintained a balanced mix of all media types!",
  },
  {
    id: "media_scholar",
    name: "Media Scholar",
    type: "exploration",
    threshold: 50,
    icon: "📚",
    description: "Explored 50+ diverse media types — true researcher!",
  },
  {
    id: "universal_explorer",
    name: "Universal Explorer",
    type: "exploration",
    threshold: 100,
    icon: "🌍",
    description: "Explored all corners of media — universal taste!",
  },

  // 🧠 9. SMART DISCOVERY BADGES
  {
    id: "first_foreign_language",
    name: "Global Viewer",
    type: "discovery",
    threshold: 1,
    icon: "🌐",
    description: "Watched or read something in a new language!",
  },
  {
    id: "first_unique_platform",
    name: "New Platform Explorer",
    type: "discovery",
    threshold: 2,
    icon: "🧭",
    description: "Discovered a new platform — expanding your reach!",
  },
  {
    id: "curious_mind",
    name: "Curious Mind",
    type: "discovery",
    threshold: 10,
    icon: "🔍",
    description: "Explored 10 different platforms or categories!",
  },
  {
    id: "trend_discoverer",
    name: "Trend Discoverer",
    type: "discovery",
    threshold: 25,
    icon: "🚀",
    description: "Found and logged trending or unique media!",
  },
  {
    id: "cultural_explorer",
    name: "Cultural Explorer",
    type: "discovery",
    threshold: 50,
    icon: "🌏",
    description: "Explored media from 10+ different countries!",
  },
  {
    id: "knowledge_seeker",
    name: "Knowledge Seeker",
    type: "discovery",
    threshold: 100,
    icon: "💡",
    description: "Discovered 100+ unique entries — true learner!",
  },
];
